version: '3'
services:
  terraform:
    container_name: 'terraform'
    image: local/terraform
    build:
      context: ./
      dockerfile: docker/terraform/Dockerfile
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-**********}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-****************}
    volumes:
      - ./src:/root/src
